services:
  app:
    image: fireflyiii/core:latest
    volumes:
      - upload:/var/www/html/storage/upload
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      SITE_OWNER: ${SITE_OWNER}
      APP_KEY: ${APP_KEY}
      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE}
      DEFAULT_LOCALE: ${DEFAULT_LOCALE}
      TZ: ${TZ}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES}
      LOG_CHANNEL: ${LOG_CHANNEL}
      APP_LOG_LEVEL: ${APP_LOG_LEVEL}
      AUDIT_LOG_LEVEL: ${AUDIT_LOG_LEVEL}
      AUDIT_LOG_CHANNEL: ${AUDIT_LOG_CHANNEL}
      PAPERTRAIL_HOST: ${PAPERTRAIL_HOST}
      PAPERTRAIL_PORT: ${PAPERTRAIL_PORT}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SOCKET: ${DB_SOCKET}
      MYSQL_USE_SSL: ${MYSQL_USE_SSL}
      MYSQL_SSL_VERIFY_SERVER_CERT: ${MYSQL_SSL_VERIFY_SERVER_CERT}
      MYSQL_SSL_CAPATH: ${MYSQL_SSL_CAPATH}
      MYSQL_SSL_CA: ${MYSQL_SSL_CA}
      MYSQL_SSL_CERT: ${MYSQL_SSL_CERT}
      MYSQL_SSL_KEY: ${MYSQL_SSL_KEY}
      MYSQL_SSL_CIPHER: ${MYSQL_SSL_CIPHER}
      PGSQL_SSL_MODE: ${PGSQL_SSL_MODE}
      PGSQL_SSL_ROOT_CERT: ${PGSQL_SSL_ROOT_CERT}
      PGSQL_SSL_CERT: ${PGSQL_SSL_CERT}
      PGSQL_SSL_KEY: ${PGSQL_SSL_KEY}
      PGSQL_SSL_CRL_FILE: ${PGSQL_SSL_CRL_FILE}
      PGSQL_SCHEMA: ${PGSQL_SCHEMA}
      CACHE_DRIVER: ${CACHE_DRIVER}
      SESSION_DRIVER: ${SESSION_DRIVER}
      REDIS_SCHEME: ${REDIS_SCHEME}
      REDIS_PATH: ${REDIS_PATH}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_USERNAME: ${REDIS_USERNAME}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_DB: ${REDIS_DB}
      REDIS_CACHE_DB: ${REDIS_CACHE_DB}
      COOKIE_PATH: ${COOKIE_PATH}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      COOKIE_SECURE: ${COOKIE_SECURE}
      COOKIE_SAMESITE: ${COOKIE_SAMESITE}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_FROM: ${MAIL_FROM}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
      MAIL_SENDMAIL_COMMAND: ${MAIL_SENDMAIL_COMMAND}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_SECRET: ${MAILGUN_SECRET}
      MAILGUN_ENDPOINT: ${MAILGUN_ENDPOINT}
      MANDRILL_SECRET: ${MANDRILL_SECRET}
      SPARKPOST_SECRET: ${SPARKPOST_SECRET}
      SEND_ERROR_MESSAGE: ${SEND_ERROR_MESSAGE}
      SEND_REPORT_JOURNALS: ${SEND_REPORT_JOURNALS}
      ENABLE_EXTERNAL_MAP: ${ENABLE_EXTERNAL_MAP}
      ENABLE_EXCHANGE_RATES: ${ENABLE_EXCHANGE_RATES}
      ENABLE_EXTERNAL_RATES: ${ENABLE_EXTERNAL_RATES}
      MAP_DEFAULT_LAT: ${MAP_DEFAULT_LAT}
      MAP_DEFAULT_LONG: ${MAP_DEFAULT_LONG}
      MAP_DEFAULT_ZOOM: ${MAP_DEFAULT_ZOOM}
      VALID_URL_PROTOCOLS: ${VALID_URL_PROTOCOLS}
      AUTHENTICATION_GUARD: ${AUTHENTICATION_GUARD}
      AUTHENTICATION_GUARD_HEADER: ${AUTHENTICATION_GUARD_HEADER}
      AUTHENTICATION_GUARD_EMAIL: ${AUTHENTICATION_GUARD_EMAIL}
      PASSPORT_PRIVATE_KEY: ${PASSPORT_PRIVATE_KEY}
      PASSPORT_PUBLIC_KEY: ${PASSPORT_PUBLIC_KEY}
      CUSTOM_LOGOUT_URL: ${CUSTOM_LOGOUT_URL}
      DISABLE_FRAME_HEADER: ${DISABLE_FRAME_HEADER}
      DISABLE_CSP_HEADER: ${DISABLE_CSP_HEADER}
      TRACKER_SITE_ID: ${TRACKER_SITE_ID}
      TRACKER_URL: ${TRACKER_URL}
      ALLOW_WEBHOOKS: ${ALLOW_WEBHOOKS}
      STATIC_CRON_TOKEN: ${STATIC_CRON_TOKEN}
      DKR_BUILD_LOCALE: ${DKR_BUILD_LOCALE}
      DKR_CHECK_SQLITE: ${DKR_CHECK_SQLITE}
      APP_NAME: ${APP_NAME}
      BROADCAST_DRIVER: ${BROADCAST_DRIVER}
      QUEUE_DRIVER: ${QUEUE_DRIVER}
      CACHE_PREFIX: ${CACHE_PREFIX}
      PUSHER_KEY: ${PUSHER_KEY}
      IPINFO_TOKEN: ${IPINFO_TOKEN}
      PUSHER_SECRET: ${PUSHER_SECRET}
      PUSHER_ID: ${PUSHER_ID}
      DEMO_USERNAME: ${DEMO_USERNAME}
      DEMO_PASSWORD: ${DEMO_PASSWORD}
      USE_RUNNING_BALANCE: ${USE_RUNNING_BALANCE}
      FIREFLY_III_LAYOUT: ${FIREFLY_III_LAYOUT}
      APP_URL: ${APP_URL}
    labels:
      - traefik.enable=${TRAEFIK_ENABLE}
      - traefik.http.services.${TRAEFIK_ROUTER_NAME}.loadbalancer.server.port=${TRAEFIK_LB_PORT}
      - traefik.http.routers.${TRAEFIK_ROUTER_NAME}.tls=${TRAEFIK_TLS}
      - traefik.http.routers.${TRAEFIK_ROUTER_NAME}.tls.certresolver=${TRAEFIK_CERT_RESOLVER}
      - traefik.http.routers.${TRAEFIK_ROUTER_NAME}.rule=${TRAEFIK_ROUTER_RULE}
    networks:
      - ${INGRESS_NETWORK}
    depends_on:
      - db

  db:
    image: mariadb:lts
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

volumes:
  upload:
  db:

networks:
  ${INGRESS_NETWORK}:
    external: true
