services:
  app:
    image: fireflyiii/core:latest
    volumes:
      - upload:/var/www/html/storage/upload
    depends_on:
      - db
  
  db:
    image: mariadb:lts
    volumes:
      - db:/var/lib/mysql
  
  cron:
    image: alpine
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/{{ FIREFLY_CRON_STATIC_TOKEN }};echo\" | crontab - && crond -f -L /dev/stdout"
    depends_on:
      - app

volumes:
  upload:
  db: