services:
  app:
    image: fireflyiii/core:latest
    volumes:
      - upload:/var/www/html/storage/upload
    depends_on:
      - db
  
  db:
    image: mariadb:lts
    volumes:
      - db:/var/lib/mysql

volumes:
  upload:
  db: